### ISSUE TITLE
Launch on the main network matic

### ISSUE THREAD

**Issue by udmteh** [rajkharvar/disperse-clone#14]
Hello. Where and what changes need to be made to make it work in the main matic network?

**Comment by rajkharvar** [comment]
Hey @udmteh.
To support matic networks. The following changes are required:
1. Deploy the contract on matic
2. Add matic contract address and blockexplorer in frontend.

**Comment by udmteh** [comment]
I can not. Friend, could you record a short video on how to assemble and run this project, I would be very grateful to you.

**Comment by udmteh** [comment]
These are my errors from the console

Error HH8: There's one or more errors in your config file:

  * Invalid value undefined for HardhatConfig.networks.ropsten.url - Expected a value of type string.
  * Invalid account: #0 for network: ropsten - Expected string, received undefined
  * Invalid value undefined for HardhatConfig.networks.rinkeby.url - Expected a value of type string.
  * Invalid account: #0 for network: rinkeby - Expected string, received undefined
  * Invalid value undefined for HardhatConfig.networks.goerli.url - Expected a value of type string.
  * Invalid account: #0 for network: goerli - Expected string, received undefined
  * Invalid value undefined for HardhatConfig.networks.kovan.url - Expected a value of type string.
  * Invalid account: #0 for network: kovan - Expected string, received undefined
  * Invalid value undefined for HardhatConfig.networks.mumbai.url - Expected a value of type string.
  * Invalid account: #0 for network: mumbai - Expected string, received undefined
  * Invalid value undefined for HardhatConfig.networks.skale.url - Expected a value of type string.
  * Invalid account: #0 for network: skale - Expected string, received undefined
  * Invalid value undefined for HardhatConfig.networks.skaleTestnetV2.url - Expected a value of type string.
  * Invalid account: #0 for network: skaleTestnetV2 - Expected string, received undefined
  
To learn more about Hardhat's configuration, please go to https://hardhat.org/config/

**Comment by rajkharvar** [comment]
Hey @udmteh 
This happens because hardhat config requires env variables. You can copy the env variables from `.env.tpl` into `.env` file, and update the required variables.

**Comment by rajkharvar** [comment]
Hey @udmteh 
I have added support polygon (matic mainnet).
